let model;
const statusText = document.getElementById("status");
const resultBox = document.getElementById("result");
const imageInput = document.getElementById("imageUpload");
const preview = document.getElementById("preview");

async function loadAI() {
    model = await mobilenet.load();
    statusText.innerText = "AI model loaded. Upload a plant leaf image.";
}

loadAI();

imageInput.addEventListener("change", async (event) => {
    const file = event.target.files[0];
    if (!file) return;

    preview.src = URL.createObjectURL(file);
    preview.style.display = "block";

    preview.onload = async () => {
        statusText.innerText = "Analyzing image with AI...";
        const predictions = await model.classify(preview);

        const top = predictions[0];

        resultBox.style.display = "block";
        resultBox.innerHTML = `
            <h3>AI Prediction</h3>
            <p><strong>Detected Pattern:</strong> ${top.className}</p>
            <p><strong>Confidence:</strong> ${(top.probability * 100).toFixed(2)}%</p>
            <p>
              <strong>Note:</strong> This result is generated by a real
              convolutional neural network running directly in your browser.
            </p>
        `;

        statusText.innerText = "Analysis complete.";
    };
});
